LatticeHashForest: lhf::MapAdapter< MapClass > Class Template Reference
lhf::MapAdapter< MapClass > Class Template Reference
#include <lhf.hpp>
Public Types
using Map = MapClass
using Key = typename Map::key_type
using MappedType = typename Map::mapped_type
using KeyValuePair = typename Map::value_type
Public Member Functions
Optional< MappedType > find (const Key &key) const
void insert (KeyValuePair &&v)
Size size () const
Map::const_iterator begin () const
Map::const_iterator end () const
String to_string () const
Protected Attributes
Map data
Detailed Description
template<typename MapClass>
class lhf::MapAdapter< MapClass >
Definition at line 728 of file lhf.hpp.
Member Typedef Documentation
Key
template<typename MapClass > using lhf::MapAdapter< MapClass >::Key = typename Map::key_type
Definition at line 731 of file lhf.hpp.
KeyValuePair
template<typename MapClass > using lhf::MapAdapter< MapClass >::KeyValuePair = typename Map::value_type
Definition at line 733 of file lhf.hpp.
Map
template<typename MapClass > using lhf::MapAdapter< MapClass >::Map = MapClass
Definition at line 730 of file lhf.hpp.
MappedType
template<typename MapClass > using lhf::MapAdapter< MapClass >::MappedType = typename Map::mapped_type
Definition at line 732 of file lhf.hpp.
Member Function Documentation
begin()
template<typename MapClass > Map::const_iterator lhf::MapAdapter< MapClass >::begin () const inline
Definition at line 760 of file lhf.hpp.
end()
template<typename MapClass > Map::const_iterator lhf::MapAdapter< MapClass >::end () const inline
Definition at line 764 of file lhf.hpp.
find()
template<typename MapClass > Optional< MappedType > lhf::MapAdapter< MapClass >::find (const Key & key) const inline
Definition at line 740 of file lhf.hpp.
Referenced by lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::is_subset(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set_single(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set_single(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::set_difference(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::set_filter(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::set_intersection(), and lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::set_union().
insert()
template<typename MapClass > void lhf::MapAdapter< MapClass >::insert (KeyValuePair && v) inline
Definition at line 750 of file lhf.hpp.
Referenced by lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set_single(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set_single(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::set_difference(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::set_filter(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::set_intersection(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::set_union(), and lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::store_subset().
size()
template<typename MapClass > Size lhf::MapAdapter< MapClass >::size () const inline
Definition at line 755 of file lhf.hpp.
Referenced by lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::dump().
to_string()
template<typename MapClass > String lhf::MapAdapter< MapClass >::to_string () const inline
Definition at line 768 of file lhf.hpp.
Referenced by lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::dump().
Member Data Documentation
data
template<typename MapClass > Map lhf::MapAdapter< MapClass >::data protected
Definition at line 736 of file lhf.hpp.
The documentation for this class was generated from the following file:
src/include/lhf/lhf.hpp