LatticeHashForest: lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder Struct Reference
lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder Struct Reference
#include <lhf.hpp>
Public Types
using PtrContainer = UniquePointer< PropertySet >
using Ptr = typename PtrContainer::pointer
Public Member Functions
PropertySetHolder (Ptr &&p)
Ptr get () const
bool is_evicted () const
Public Attributes
PtrContainer ptr
Detailed Description
template<typename PropertyT, typename PropertyLess = DefaultLess<PropertyT>, typename PropertyHash = DefaultHash<PropertyT>, typename PropertyEqual = DefaultEqual<PropertyT>, typename PropertyPrinter = DefaultPrinter<PropertyT>, typename Nesting = NestingNone<PropertyT>, Size BLOCK_SIZE = LHF_DEFAULT_BLOCK_SIZE, Size BLOCK_MASK = LHF_DEFAULT_BLOCK_MASK>
struct lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder
Definition at line 1226 of file lhf.hpp.
Member Typedef Documentation
Ptr
template<typename PropertyT , typename PropertyLess = DefaultLess<PropertyT>, typename PropertyHash = DefaultHash<PropertyT>, typename PropertyEqual = DefaultEqual<PropertyT>, typename PropertyPrinter = DefaultPrinter<PropertyT>, typename Nesting = NestingNone<PropertyT>, Size BLOCK_SIZE = LHF_DEFAULT_BLOCK_SIZE, Size BLOCK_MASK = LHF_DEFAULT_BLOCK_MASK> using lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder::Ptr = typename PtrContainer::pointer
Definition at line 1228 of file lhf.hpp.
PtrContainer
template<typename PropertyT , typename PropertyLess = DefaultLess<PropertyT>, typename PropertyHash = DefaultHash<PropertyT>, typename PropertyEqual = DefaultEqual<PropertyT>, typename PropertyPrinter = DefaultPrinter<PropertyT>, typename Nesting = NestingNone<PropertyT>, Size BLOCK_SIZE = LHF_DEFAULT_BLOCK_SIZE, Size BLOCK_MASK = LHF_DEFAULT_BLOCK_MASK> using lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder::PtrContainer = UniquePointer<PropertySet>
Definition at line 1227 of file lhf.hpp.
Constructor & Destructor Documentation
PropertySetHolder()
template<typename PropertyT , typename PropertyLess = DefaultLess<PropertyT>, typename PropertyHash = DefaultHash<PropertyT>, typename PropertyEqual = DefaultEqual<PropertyT>, typename PropertyPrinter = DefaultPrinter<PropertyT>, typename Nesting = NestingNone<PropertyT>, Size BLOCK_SIZE = LHF_DEFAULT_BLOCK_SIZE, Size BLOCK_MASK = LHF_DEFAULT_BLOCK_MASK> lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder::PropertySetHolder (Ptr && p) inline
Definition at line 1232 of file lhf.hpp.
Member Function Documentation
get()
template<typename PropertyT , typename PropertyLess = DefaultLess<PropertyT>, typename PropertyHash = DefaultHash<PropertyT>, typename PropertyEqual = DefaultEqual<PropertyT>, typename PropertyPrinter = DefaultPrinter<PropertyT>, typename Nesting = NestingNone<PropertyT>, Size BLOCK_SIZE = LHF_DEFAULT_BLOCK_SIZE, Size BLOCK_MASK = LHF_DEFAULT_BLOCK_MASK> Ptr lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder::get () const inline
Definition at line 1234 of file lhf.hpp.
Referenced by lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set(), lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set_single(), and lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::register_set_single().
is_evicted()
template<typename PropertyT , typename PropertyLess = DefaultLess<PropertyT>, typename PropertyHash = DefaultHash<PropertyT>, typename PropertyEqual = DefaultEqual<PropertyT>, typename PropertyPrinter = DefaultPrinter<PropertyT>, typename Nesting = NestingNone<PropertyT>, Size BLOCK_SIZE = LHF_DEFAULT_BLOCK_SIZE, Size BLOCK_MASK = LHF_DEFAULT_BLOCK_MASK> bool lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder::is_evicted () const inline
Definition at line 1238 of file lhf.hpp.
Member Data Documentation
ptr
template<typename PropertyT , typename PropertyLess = DefaultLess<PropertyT>, typename PropertyHash = DefaultHash<PropertyT>, typename PropertyEqual = DefaultEqual<PropertyT>, typename PropertyPrinter = DefaultPrinter<PropertyT>, typename Nesting = NestingNone<PropertyT>, Size BLOCK_SIZE = LHF_DEFAULT_BLOCK_SIZE, Size BLOCK_MASK = LHF_DEFAULT_BLOCK_MASK> PtrContainer lhf::LatticeHashForest< PropertyT, PropertyLess, PropertyHash, PropertyEqual, PropertyPrinter, Nesting, BLOCK_SIZE, BLOCK_MASK >::PropertySetHolder::ptr mutable
Definition at line 1230 of file lhf.hpp.
The documentation for this struct was generated from the following file:
src/include/lhf/lhf.hpp